# Generated by Django 3.2.5 on 2021-11-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('userpass', models.CharField(max_length=30, verbose_name='密码')),
                ('useremail', models.EmailField(max_length=30, verbose_name='邮箱')),
                ('usertype', models.CharField(max_length=30, verbose_name='用户类型')),
            ],
        ),
    ]
